# Generated by Django 3.2.5 on 2021-07-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data_analytics', models.BooleanField()),
                ('service_analytics', models.BooleanField()),
                ('voice_analytics', models.BooleanField()),
                ('queue_stats', models.BooleanField()),
                ('voice_stats', models.BooleanField()),
                ('video', models.BooleanField()),
                ('smart_access', models.BooleanField()),
                ('diagrams', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_task.group')),
            ],
        ),
    ]
