# Generated by Django 3.2.5 on 2021-07-05 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 20, 1, 44, 482189, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='group',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 20, 1, 44, 482207, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 20, 1, 44, 482602, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 20, 1, 44, 482617, tzinfo=utc)),
        ),
    ]
